#!/bin/bash

for INPUT in "$@"
do

docker start $(docker ps -aq --format '{{.Names}}'  | grep "^$INPUT"  | awk '{print $1}')

# | awk '{print $1}' | xargs -I {} docker start {} | xargs -I {}




done
