#!/bin/bash
echo ""
echo ""
echo "GIT STATUS"
git status

echo ""
echo ""
echo "GIT ADD ."
git add .

echo ""
echo ""
echo "GIT COMMIT"
read -p "ENTER COMMIT COMMENT (Default: Minor Changes): " comment
comment=${comment:-Minor Changes}
git commit -m "$comment"
