#!/bin/bash
echo ""
echo ""
echo "GIT STATUS"
git status

echo ""
echo ""
echo "GIT ADD ."
git add .

echo ""
echo ""
echo "GIT COMMIT"
git commit -m "minor changes"

echo ""
echo ""
echo "GIT PUSH"
git push origin master
