#!/bin/bash

branch=$(git branch | grep \* | cut -d ' ' -f2)


echo ""
echo ""
echo "GIT STATUS ."
git status


echo ""
echo ""
echo "GIT COMMIT"
git commit

echo ""
echo ""
echo "GIT PUSH"
read -p "ENTER BRANCH NAME (Current Branch: $branch): " name
name=${name:-$branch}
git push origin $name

echo ""
echo ""
echo "CHANGELOG.md generate"
FILE=CHANGELOG.md
if [ ! -f "$FILE" ]
then
    touch $FILE
fi
(echo ""; echo ""; echo ""; git log --name-status HEAD^..HEAD | cat - "$FILE") >  temp && mv temp "$FILE"
