#!/bin/bash
echo "git submodule update --init --recursive"
git submodule update --init --recursive

echo ""
echo "git submodule update --remote --recursive"
#git submodule update --remote --recursive

echo ""
echo "git submodule foreach git checkout master"
git submodule foreach --recursive git checkout master

echo ""
echo "git submodule foreach git reset --hard master"
git submodule foreach --recursive git reset --hard master

echo ""
echo "git submodule foreach git pull origin master"
git submodule foreach --recursive git pull origin master
