#!/bin/bash

echo ""
echo ""
echo "AUTO-CHANGELOG"
auto-changelog

branch=$(git branch | grep \* | cut -d ' ' -f2)


echo ""
echo ""
echo "GIT STATUS ."
git status

echo ""
echo ""
echo "GIT ADD ."
git add .


echo ""
echo ""
echo "GIT COMMIT"
read -p "ENTER COMMIT COMMENT (Default: Minor Changes): " comment
comment=${comment:-Minor Changes}
git commit -m "$comment"

echo ""
echo ""
echo "GIT PUSH"
read -p "ENTER BRANCH NAME (Current Branch: $branch): " name
name=${name:-$branch}
git push origin $name
