#!/bin/bash

branch=$(git branch | grep \* | cut -d ' ' -f2)


echo ""
echo ""
echo "GIT STATUS"
git status

echo ""
echo ""
echo "GIT PULL ORIGIN $branch ."
git pull origin $branch


echo ""
echo ""
echo "COMPOSER UPDATE --NO-DEV"
composer update --no-dev
