#!/bin/bash
# Getting current branch name
branch=$(git branch | grep \* | cut -d ' ' -f2)
echo "Current branch: $branch"

echo ""
echo ""
echo "GIT STATUS ."
git status

echo ""
echo ""
echo "GIT ADD ."
git add .

echo ""
echo ""
echo "GIT COMMIT"
git commit

echo ""
echo ""
echo "GIT PUSH"
read -p "ENTER BRANCH NAME (Current Branch: $branch): " name
name=${name:-$branch}
git push origin $name

echo ""
echo ""
echo "GIT MERGE TO MASTER"
git fetch . $name:master

echo ""
echo ""
echo "GIT PUSH ORIGIN MASTER"
git_add_commit_push_master
