#!/bin/bash
# Getting current branch name
branch=$(git branch | grep \* | cut -d ' ' -f2)
echo "Current branch: $branch"

echo ""
echo ""
echo "GIT STATUS ."
git status

echo ""
echo ""
echo "GIT ADD ."
git add .

echo ""
echo ""
echo "GIT COMMIT"
read -p "ENTER COMMIT COMMENT (Default: Minor Changes): " comment
comment=${comment:-Minor Changes}
git commit -m "$comment"

echo ""
echo ""
echo "GIT PUSH"
read -p "ENTER BRANCH NAME (Current Branch: $branch): " name
name=${name:-$branch}
git push production $name

echo ""
echo ""
echo "GIT MERGE TO MASTER"
git fetch . $name:master

echo ""
echo ""
echo "GIT PUSH PRODUCTION MASTER"
git_add_push_master