#!/bin/bash
echo ""
echo ""
echo "GIT STATUS"
git status

echo ""
echo ""
echo "GIT ADD ."
git add .

echo ""
echo ""
echo "GIT COMMIT"
git commit -m "minor changes"

echo ""
echo ""
echo "GIT PUSH"
git push origin master



echo ""
echo ""
echo "CHANGELOG.md generate"
FILE=CHANGELOG.md
if [ ! -f "$FILE" ]
then
    touch $FILE
fi
(echo ""; echo ""; echo ""; git log --name-status HEAD^..HEAD | cat - "$FILE") >  temp && mv temp "$FILE"
