#!/bin/bash

function gitUpdate(){
    if [ -z $1 ]
    then
    echo "git submodule update --init ./"
    git submodule update --init ./
    echo "git checkout master"
    git checkout master
    else
    echo "git submodule update --init $1"
    git submodule update --init $1

    fi
}



gitUpdate $1

