#!/bin/bash



echo ""
echo ""
echo "GIT DESCRIBE --tags"
git describe --tags

echo ""
echo ""
echo "GIT ADD ."
git add .

echo ""
echo ""
echo "GIT TAG -a -m"
read -p "ENTER TAG COMMENT: " comment

echo ""
read -p "ENTER TAG NAME: " tag_name
git commit -m "$comment"

echo ""
echo ""
echo "git tag -a -m $comment $tag_name"
git tag -a -m "$comment" "$tag_name"

echo ""
echo ""
echo "git push origin $tag_name"
git push origin $tag_name

