#!/bin/bash

find . -type d \( -name .git -o -name gulp-workflow \)  -prune -o -type f \( ! -iname "modman" ! -iname ".gitmodules" ! -iname "composer.json" ! -iname ".gitignore" ! -iname "README.md" \) -printf "%P\n"> modman