#!/bin/bash

function php_switch (){
	sudo a2dismod php$2 ; sudo a2enmod php$1 ; sudo systemctl restart apache2.service
	sudo update-alternatives --set php /usr/bin/php$1
	sudo systemctl restart apache2.service
	sudo systemctl stop apache2.service
	sudo update-rc.d apache2 disable
}

php_switch $2 $1

## Usage:
## php_switch current_php new_php
### php list: php5.6 php7.1 php7.2
