#!/bin/bash

function php_switch (){
	sudo a2dismod $2 ; sudo a2enmod $1 ; sudo systemctl restart apache2.service
	sudo update-alternatives --set php /usr/bin/$1
	sudo systemctl restart apache2.service
}

php_switch $2 $1

## Usage:
## php_switch current_php new_php
### php list: php5.6 php7.1 php7.2
